---
title: "Data Visualization with R - Part 2"
author: "Junho Lee"
date: "1/13/2019"
output: html_document
---

Prep
```{r}
library(ggplot2)
library(ggplot2movies)
```

2-D bin chart 

```{r}
pl <- ggplot(movies,aes(x=year,y=rating))
print(pl + geom_bin2d())
```

```{r}
pl <- ggplot(movies,aes(x=year,y=rating))
pl2 <- pl + geom_bin2d() + scale_fill_gradient(high='red',low='green')
print(pl2)
```

```{r}
pl2 <- pl + geom_bin2d(binwidth=(c(3,1))) + scale_fill_gradient(high='red',low='green')
print(pl2)
```

```{r}
pl2 <- pl + geom_density2d()
print(pl2)
```

##### Coordinates and Faceting
```{r}
pl <- ggplot(mpg,aes(x=displ,y=hwy)) + geom_point()
print(pl)
```

```{r}
pl2 <- pl + coord_cartesian(xlim = c(1,4),ylim = c(15,30))
print(pl2)
```

```{r}
pl2 <- pl + coord_fixed(ratio = 1/3)
print(pl2)
```

```{r}
pl2 <- pl + facet_grid(. ~ cyl)
print(pl2)
```

```{r}
pl2 <- pl + facet_grid(drv ~ .)
print(pl2)
```

##### Themes
```{r}
# theme_set(theme_minimal())
pl <- ggplot(mtcars,aes(x=wt,y=mpg)) + geom_point()
print(pl + theme_dark())
```

```{r}
# install.packages('ggthemes')
library(ggthemes)
print(pl + theme_economist())
```

```{r}
print(pl + theme_fivethirtyeight())
```