DATA HOSPITALS;
	INPUT PatientID $ HospitalBill Age Diagnosis $ Gender $ State $; 
	DATALINES;
	1 500 5 SoreThroat 1 NY
	2 1500 68 Fall 2 CA
	3 2000 94 Parkinsons 1 CA
	4 250 15 Checkup 1 NY
	5 25000 9 Cancer 2 CA
	6 900 64 Diabetes 1 CA
	;
RUN;

PROC REPORT DATA=WORK.HOSPITALS;
COLUMN STATE GENDER HOSPITALBILL, (SUM MEAN);
DEFINE STATE / GROUP;
DEFINE GENDER / GROUP;
RUN;

PROC REPORT DATA=WORK.HOSPITALS;
COLUMN STATE GENDER HOSPITALBILL, MEDIAN N; /* N is a keyword to count records */
DEFINE STATE / GROUP;
DEFINE GENDER / GROUP;
RUN;