DATA HOSPITALS;
	INPUT PatientID $ HospitalBill Age Diagnosis $ Gender $ State $; 
	DATALINES;
	1 500 5 SoreThroat 1 NY
	2 1500 68 Fall 2 CA
	3 2000 94 Parkinsons 1 CA
	4 250 15 Checkup 1 NY
	5 25000 9 Cancer 2 CA
	6 900 64 Diabetes 1 CA
	;
RUN;

DATA OCCUPATION;
	INPUT PatientID $ JOBTYPE $;
	DATALINES;
	1 KINDER
	2 ACTUARY
	3 RETIRED
	4 HS
	5 ELEM
	;
RUN;

/*Advantage over Merge: No need to sort in advance*/
PROC SQL;
CREATE TABLE SQL_COMBINE AS
SELECT HOSPITALS.PATIENTID, HOSPITALS.AGE, OCCUPATION.JOBTYPE
FROM HOSPITALS LEFT JOIN OCCUPATION
ON HOSPITALS.PATIENTID = OCCUPATION.PATIENTID;
RUN;