DATA HOSPITALS;
	INPUT PatientID $ HospitalBill Age Diagnosis $ Gender $ State $; 
	DATALINES;
	1 500 5 SoreThroat 1 NY
	2 1500 68 Fall 2 CA
	3 2000 94 Parkinsons 1 CA
	4 250 15 Checkup 1 NY
	5 25000 9 Cancer 2 CA
	6 900 64 Diabetes 1 CA
	;
RUN;

PROC MEANS DATA=WORK.HOSPITALS;
RUN;

PROC SORT DATA=WORK.HOSPITALS;
BY STATE;
RUN;

PROC MEANS DATA=WORK.HOSPITALS MEAN N SUM;
BY STATE;
RUN;

PROC SORT DATA=WORK.HOSPITALS;
BY STATE GENDER;
RUN;

PROC MEANS DATA=WORK.HOSPITALS MEAN N SUM;
BY STATE GENDER;
RUN;