DATA HOSPITALS;
	INPUT PatientID $ HospitalBill Age Diagnosis $ Gender $ State $; 
	DATALINES;
	1 500 5 SoreThroat 1 NY
	2 1500 68 Fall 2 CA
	3 2000 94 Parkinsons 1 CA
	4 250 15 Checkup 1 NY
	5 25000 9 Cancer 2 CA
	6 900 64 Diabetes 1 CA
	;
RUN;

DATA OCCUPATION;
	INPUT PatientID $ JOBTYPE $;
	DATALINES;
	1 KINDER
	2 ACTUARY
	3 RETIRED
	4 HS
	5 ELEM
	;
RUN;

/*Sort data first*/
PROC SORT DATA=WORK.HOSPITALS;
BY PATIENTID;
RUN;

PROC SORT DATA=WORK.OCCUPATION;
BY PATIENTID;
RUN;

DATA COMBINE;
MERGE WORK.HOSPITALS (IN=A) WORK.OCCUPATION (IN=B); /*Renaming temporally in this dataset*/
BY PATIENTID;
IF A AND B; /*Merge like INNER JOIN*/
RUN;

DATA COMBINE_V2;
MERGE WORK.HOSPITALS (IN=A) WORK.OCCUPATION (IN=B); /*Renaming temporally in this dataset*/
BY PATIENTID;
IF A; /*Merge like LEFT JOIN*/
RUN;

DATA COMBINE_V3;
MERGE WORK.HOSPITALS (IN=A) WORK.OCCUPATION (IN=B); /*Renaming temporally in this dataset*/
BY PATIENTID;
IF B; /*Merge like RIGHT JOIN*/
RUN;